CREATE TABLE IF NOT EXISTS USERS (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(500) NOT NULL,
date_Of_Birth TIMESTAMP,
password VARCHAR(500) NOT NULL
);
CREATE TABLE IF NOT EXISTS ACCOUNT (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
user_id BIGINT UNIQUE NOT NULL,
balance DECIMAL(15,2) NOT NULL,
FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS EMAIL_DATA (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
user_id BIGINT NOT NULL,
email VARCHAR(200) UNIQUE NOT NULL,
FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS PHONE_DATA  (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
user_id BIGINT NOT NULL,
phone VARCHAR(13) UNIQUE NOT NULL,
FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
);
ALTER TABLE USERS ADD COLUMN ACCOUNT_ID BIGINT;
ALTER TABLE USERS ADD CONSTRAINT FK_USERS_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(id);

