CREATE TABLE USERS (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(500) NOT NULL,
date_of_birth TIMESTAMP,
password VARCHAR(500) NOT NULL
);
CREATE TABLE ACCOUNT (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
user_id BIGINT UNIQUE NOT NULL,
balance DECIMAL(15,2) NOT NULL,
FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE
);
CREATE TABLE EMAIL_DATA (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
user_id BIGINT NOT NULL,
email VARCHAR(200) UNIQUE NOT NULL,
FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE
);
CREATE TABLE PHONE_DATA  (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
user_id BIGINT NOT NULL,
phone VARCHAR(13) UNIQUE NOT NULL,
FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE
)
